on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.digitalocean.com
      REPOSITORY: eropad
      TOKEN: redacted # use env secret
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ env.TOKEN }}
          password: ${{ env.TOKEN }}
          registry: ${{ env.REGISTRY }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/eropad:${{ github.sha }}
      - uses: actions/checkout@v3
        with:
          repository: eropad/gitops
          token: ${{ secrets.GH_PAT }}
          path: gitops
      - uses: mikefarah/yq@v4.30.8
        with:
          cmd: TAG=${{ env.REGISTRY }}/${{ env.REPOSITORY }}/eropad:${{ github.sha }} yq e -i ".image = strenv(TAG)" gitops/environments/ghost.prod.yaml
      - run: cd gitops && git config user.name ${{ github.actor }}
      - run: cd gitops && git config user.email ${{ github.event.pusher.email }}
      - run: cd gitops && git add environments/ghost.prod.yaml
      - run: cd gitops && git commit -m "${{ github.event.head_commit.message }}"
      - run: cd gitops && git pull --rebase
      - run: cd gitops && git push
